version: '3.8'

services:
  ner-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - LOG_LEVEL=INFO
      - SPACY_MODEL=en_core_web_sm
      - MAX_TEXT_LENGTH=1000000
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
