version: '3.8'

services:
  api-gateway-service:
    build: .
    ports:
      - "8005:8005"
    environment:
      - LOG_LEVEL=INFO
      - JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REDIS_URL=redis://redis:6379/1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=1
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_REQUESTS_PER_MINUTE=60
      - INGESTION_SERVICE_URL=http://ingestion-service:8003
      - OCR_SERVICE_URL=http://ocr-service:8000
      - NER_SERVICE_URL=http://ner-service:8001
      - EMBEDDING_SERVICE_URL=http://embedding-service:8002
      - QUERY_SERVICE_URL=http://query-service:8005
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
