version: '3.8'

services:
  ocr-service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - OCR_DPI=300
      - MAX_FILE_SIZE_MB=10
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
